apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  externalTrafficPolicy: Cluster
  externalIPs:
    - 10.0.1.2 # Preferred IP address
  ports:
    - port: 80
      targetPort: 8080
